import {
  onFormInit,
  onFormMount,
  onFormUnmount,
  onFormReact,
  onFormValuesChange,
  onFormInitialValuesChange,
  onFormInputChange,
  onFormSubmit,
  onFormSubmitStart,
  onFormSubmitEnd,
  onFormSubmitFailed,
  onFormSubmitSuccess,
  onFormSubmitValidateStart,
  onFormSubmitValidateEnd,
  onFormSubmitValidateFailed,
  onFormSubmitValidateSuccess,
  onFormValidateStart,
  onFormValidateEnd,
  onFormValidateFailed,
  onFormValidateSuccess,
  onFieldInit,
  onFieldMount,
  onFieldUnmount,
  onFieldReact,
  onFieldChange,
  onFieldValueChange,
  onFieldInitialValueChange,
  onFieldInputValueChange,
  onFieldValidateStart,
  onFieldValidateEnd,
  onFieldValidateFailed,
  onFieldValidateSuccess,
} from '@formily/core'

/** formEffectsMap */
export const formEffectsMap = {
  onFormInit,
  onFormMount,
  onFormUnmount,
  onFormReact,
  onFormValuesChange,
  onFormInitialValuesChange,
  onFormInputChange,
  onFormSubmit,
  onFormSubmitStart,
  onFormSubmitEnd,
  onFormSubmitFailed,
  onFormSubmitSuccess,
  onFormSubmitValidateStart,
  onFormSubmitValidateEnd,
  onFormSubmitValidateFailed,
  onFormSubmitValidateSuccess,
  onFormValidateStart,
  onFormValidateEnd,
  onFormValidateFailed,
  onFormValidateSuccess,
} as const

/** fieldEffectsMap */
export const fieldEffectsMap = {
  onFieldInit,
  onFieldMount,
  onFieldUnmount,
  onFieldReact,
  onFieldChange,
  onFieldValueChange,
  onFieldInitialValueChange,
  onFieldInputValueChange,
  onFieldValidateStart,
  onFieldValidateEnd,
  onFieldValidateFailed,
  onFieldValidateSuccess,
} as const
